
module.exports = Object.freeze({
    MODAL_BODY_TYPES: {
        USER_DETAIL: "USER_DETAIL",
        DEFAULT: "",
        CREATE_MAINTENANCE: 'CREATE_MAINTENANCE',
        EDIT_MAINTENANCE: 'EDIT_MAINTENANCE',
        CONFIRM_DELETE_MAINTENANCE: 'CONFIRM_DELETE_MAINTENANCE',
        CREATE_VEHICLE: 'CREATE_VEHICLE',
        EDIT_VEHICLE: 'EDIT_VEHICLE',
        CONFIRM_DELETE_VEHICLE: 'CONFIRM_DELETE_VEHICLE'
    },

    RIGHT_DRAWER_TYPES: {
        NOTIFICATION: "NOTIFICATION",
    }
});
